[package]
name = "ousia_derive"
version = "1.0.0"
edition = "2024"

[lib]
name = "ousia_derive"
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "parsing"] }
quote = "1"
proc-macro2 = "1"
proc-macro-crate = "2.0"
